bus.attach(bus.device("main_ram"), 0, 24)
bus.attach(bus.device("via2", emulator), 0x7FE0, 5)
local srom, srombits = bus.device("rom", "smallrom")
bus.attach(srom, 0x8000, srombits)
local from, frombits = bus.device("rom", "forth")
bus.attach(from, 0x200000, frombits)
-- local romfs, romfsbits = bus.device("rom", "../of816-gosxb/romfs")
-- bus.attach(romfs, 0x220000, romfsbits)
